version = [2, 5]

[adsp]
name = "tgl"
machine_id = 10
image_size = "0x100000"

[[adsp.mem_zone]]
type = "ROM"
base = "0x9F180000"
size = "0x00002000"
[[adsp.mem_zone]]
type = "IMR"
base = "0xB0038000"
size = "0x100000"
[[adsp.mem_zone]]
type = "SRAM"
base = "0xBE040000"
size = "0x100000"

[cse]
partition_name = "ADSP"
[[cse.entry]]
name = "ADSP.man"
offset = "0x5c"
length = "0x464"
[[cse.entry]]
name = "cavs0015.met"
offset = "0x4c0"
length = "0x70"
[[cse.entry]]
name = "cavs0015"
offset = "0x540"
length = "0x0"  # calculated by rimage

[css]

[signed_pkg]
name = "ADSP"
[[signed_pkg.module]]
name = "cavs0015.met"

[adsp_file]
[[adsp_file.comp]]
base_offset = "0x2000"

[fw_desc.header]
name = "ADSPFW"
load_offset = "0x30000"
